const sidebarBase = [
  {
    text: "Html",
    items: [
      { text: "Introduction", link: "/basic/html/introduction" },
      { text: "HTML元素", link: "/basic/html/element" },
      { text: "HTML属性", link: "/basic/html/attribute" },
      { text: "Input元素", link: "/basic/html/input" },
      { text: "Table元素", link: "/basic/html/table" },
      { text: "Canvas元素", link: "/basic/html/canvas" },
      { text: "Interview", link: "/basic/html/interview" },
    ],
  },
  {
    text: "CSS",
    items: [
      { text: "Introduction", link: "/basic/css/introduction" },
      { text: "基础", link: "/basic/css/css" },
      { text: "flex", link: "/basic/css/flex" },
      { text: "grid", link: "/basic/css/grid" },
      { text: "居中", link: "/basic/css/center" },
      { text: "常见布局", link: "/basic/css/layout" },
      { text: "BFC", link: "/basic/css/bfc" },
      { text: "position", link: "/basic/css/position" },
      { text: "过渡与动画", link: "/basic/css/过渡与动画" },
      { text: "Interview", link: "/basic/css/interview" },
    ],
  },
  {
    text: "JavaScript",
    items: [
      { text: "Introduction", link: "/basic/javascript/introduction" },
      { text: "基础", link: "/basic/javascript/base" },
      { text: "类型和语法", link: "/basic/javascript/类型和语法" },
      { text: "Object", link: "/basic/javascript/object" },
      { text: "String", link: "/basic/javascript/String" },
      { text: "Array", link: "/basic/javascript/Array" },
      { text: "类型转换", link: "/basic/javascript/类型转换" },
      { text: "this", link: "/basic/javascript/this" },
      { text: "原型和原型链", link: "/basic/javascript/prototype" },
      { text: "同步和异步", link: "/basic/javascript/async" },
      { text: "闭包", link: "/basic/javascript/闭包" },
      { text: "EventLoop", link: "/basic/javascript/eventLoop" },
      { text: "正则", link: "/basic/javascript/正则表达式" },
      { text: "节流和防抖", link: "/basic/javascript/节流和防抖" },
      { text: "ES6", link: "/basic/javascript/ES6" },
      { text: "DOM", link: "/basic/javascript/DOM" },
      { text: "BOM", link: "/basic/javascript/BOM" },
      { text: "其他", link: "/basic/javascript/other" },
      { text: "Interview", link: "/basic/javascript/interview" },
    ],
  },
];
export default sidebarBase;
