export default [
  {
    text: "JavaScript",
    items: [
      { text: "Introduction", link: "/javascript/introduction" },
      { text: "类型和语法", link: "/javascript/type" },
      { text: "String", link: "/javascript/String" },
      { text: "Array", link: "/javascript/Array" },
      { text: "Object", link: "/javascript/object" },
      { text: "Class", link: "/javascript/class" },
      { text: "类型转换", link: "/javascript/type-conversion" },
      { text: "原型和原型链", link: "/javascript/prototype" },
      { text: "this", link: "/javascript/this" },
      { text: "闭包", link: "/javascript/closure" },
      { text: "节流和防抖", link: "/javascript/throttle-debounce" },
      { text: "同步和异步", link: "/javascript/async" },
      { text: "EventLoop", link: "/javascript/eventLoop" },
      { text: "正则", link: "/javascript/regexp" },
      { text: "ES6", link: "/javascript/ES5+" },
      { text: "DOM", link: "/javascript/DOM" },
      { text: "BOM", link: "/javascript/BOM" },
      { text: "代理和反射", link: "/javascript/proxy-reflect" },
      { text: "Broadcast Channel API", link: "/javascript/broadcast-channel-API" },
      { text: "Web Speech API", link: "/javascript/web-speech-api" },
      { text: "Intersection Observer API", link: "/javascript/intersection-observer-API" },
      { text: "其他", link: "/javascript/other" },
    ],
  },
];
